export interface Part2 {
    ID: number,
    LessonID: number,
    urlAudio: string,
    Answer: string,
    A: string,
    B: string,
    C: string,
    Question: string,
    keyA: string,
    keyB: string,
    keyC: string,
    keyChoose: string,
    keyQuestion: boolean,
    currentTime: number,
    duration: number,
    process: number,
    cssKeyA: string,
    cssKeyB: string,
    cssKeyC: string, 
    isPlay: boolean,
    media: any,
    isChoosen: boolean
}